### ISSUE TITLE
Shake extractor requirese large amount of memory 

### ISSUE THREAD

**Issue by enra64** [felixmusmann/jointly#3]
The shake extractor can degrade heavily in terms of memory performance because `helpers.get_equidistant_signals` works by putting everything in a giant DataFrame and then resamples that giant dataframe.

This can be avoided by sequentially resampling the data, however,  which resampling method is the best should be discussed.

```python
def get_equidistant_signals(signals, frequency):
    """Returns copy of dataframe with signals
    sampled equidistantly at the specified frequency.
    """
    freq = '{}N'.format(int(1e9 / frequency))

    interpolated = {}
    for column in signals.columns:
        interpolated[column] = signals[column].dropna().resample(freq).nearest()

    df = pd.DataFrame(interpolated, index=pd.date_range(start=pd.to_datetime(signals.index.min(), unit='s'),
                                        end=pd.to_datetime(signals.index.max(), unit='s'),
                                        freq=freq))

    # df = pd.DataFrame(index=pd.date_range(start=pd.to_datetime(signals.index.min(), unit='s'),
    #                                     end=pd.to_datetime(signals.index.max(), unit='s'),
    #                                     freq=freq))
    # df = df.join(signals, how='outer')
    # df = df.interpolate(method='time', limit_area='inside').resample(freq).asfreq()
    return df
```

Note further that the freq calculation is now done in nanosecond intervals to avoid truncation.

**Comment by felixmusmann** [comment]
Hi @enra64,

thank you for your input. You're right, that is definitely something that needs improvement. I'm currently not involved in the development of the module and it also moved to the following repository: https://github.com/hpi-dhc/jointly. Would you be so kind to reopen your issues (this and #2) there? I will mark this repository as archived with a link to the new one.

Cheers
